# Generated by Django 3.1.4 on 2020-12-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_cd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountapp.company'),
        ),
    ]
