# Generated by Django 3.1.4 on 2020-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_user_company_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
