# Generated by Django 3.1.4 on 2020-12-09 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_user_company_cd'),
        ('threadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='accountapp.company'),
        ),
    ]
