# Generated by Django 3.1.4 on 2020-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadapp', '0002_auto_20201209_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
